services:
  - type: web
    name: contacto
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: EMAIL_USER
        value: javierconpec@gmail.com
      - key: EMAIL_PASS
        value: zwku ctuc owqq loxg
